// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MergePDFs(arg1) {
  return window['go']['main']['App']['MergePDFs'](arg1);
}

export function OpenPDFsDialog() {
  return window['go']['main']['App']['OpenPDFsDialog']();
}

export function ReadPDFBytes(arg1) {
  return window['go']['main']['App']['ReadPDFBytes'](arg1);
}

export function SavePDFDialog(arg1) {
  return window['go']['main']['App']['SavePDFDialog'](arg1);
}
