// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function MergePDFs(arg1:main.MergeRequest):Promise<void>;

export function OpenPDFsDialog():Promise<Array<main.Document>>;

export function ReadPDFBytes(arg1:string):Promise<Array<number>>;

export function SavePDFDialog(arg1:string):Promise<string>;
